//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YummyTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSearch
    {
        public int ID { get; set; }
        public string RestaurantImg { get; set; }
        public string RestaurantName { get; set; }
        public Nullable<double> Rating { get; set; }
        public string RestaurantAddress { get; set; }
        public string RestaurantPhone { get; set; }
        public string Latlng { get; set; }
        public string TypeName { get; set; }
        public string Mon { get; set; }
        public string Tue { get; set; }
        public string Wed { get; set; }
        public string Thu { get; set; }
        public string Fri { get; set; }
        public string Sat { get; set; }
        public string Sun { get; set; }
        public string PlaceId { get; set; }
        public int RestaurantId { get; set; }
        public string Type { get; set; }
        public Nullable<double> Cost { get; set; }
        public byte[] ImgBytes { get; set; }
    }
}
